### ISSUE TITLE
UnhandledPromiseRejectionWarning - in newer tfjs version 1.7.2

### ISSUE THREAD

**Issue by guillad** [thebigpotatoe/node-red-contrib-face-recognition#10]
UnhandledPromiseRejectionWarning Error in newer tfjs 1.7.2 version.

27 Apr 17:26:22 - [error] (node:2744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

comment: latest Tensorflow,js is now fixed and working fine with other node-red nodes, 
like: node-red-contrib-tfjs-coco-ssd

**Comment by thebigpotatoe** [comment]
I am slightly confused as to what you're trying to point out here?

**Comment by ozett** [comment]
the clear up confusion: do i have to install a node-red  specific node to get tensorflow?

https://flows.nodered.org/node/node-red-contrib-tensorflow

or like the readme.md stated do the command line-version with npm

??
npm install @tensorflow/tfjs-node

i dont want to get into touble. what is the "error-less" way to accelerate face-detection?

**Comment by thebigpotatoe** [comment]
The package should run by itself. But to get the most out of your hardware such as graphics cards and such, you can optionally install the tensrflow tf package. This is stated in the readme on and which versions last worked for this package. It is most likely outdated so you will have to fiddle around with the packages stated there to find what works.

**Comment by thebigpotatoe** [comment]
Completely misread that last comment. 

I know it's a touch late, but I know the CLI version works most of the time. Not sure about the node version; have not tried it. What I do know is I have not found another version of the tfjs-node that actually works. You can see there are issues with the repo from that node and the source code.

Did you mange to give it a go?
