### ISSUE TITLE
fresh install - no fonts on detection

### ISSUE THREAD

**Issue by ozett** [thebigpotatoe/node-red-contrib-face-recognition#12]
installed all on fresh ubuntu 20.40 lts server,
with node-red raspian script and face-detection with command-line like here stated,
but fonts on detected image missing.
what to do? thanx for help...

![image](https://user-images.githubusercontent.com/5937811/83914371-6708e280-a771-11ea-831a-c3c3a98bc5fc.png)

(by the way: i had to delete the image node and drag it new onto the flow to get it work)

**Comment by ozett** [comment]
i found this error with missing fonts:
```
5 Jun 19:10:40 - [info] [Face-api.js : cde93ab3.8f0968 : Child Node] - Loaded models
5 Jun 19:10:58 - [error] Fontconfig error: Cannot load default config file

```

but than i found your hint to install depencendies here:
https://github.com/thebigpotatoe/node-red-contrib-face-recognition/issues/4#issuecomment-579088420

i will give it a try:
```
sudo apt-get update 
$ sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev 
```

**Comment by thebigpotatoe** [comment]
Going to close this since its a duplicate
