### ISSUE TITLE
Compatibility issue witn Node-Red V1.1.2

### ISSUE THREAD

**Issue by guillad** [thebigpotatoe/node-red-contrib-face-recognition#13]
Thanks again for the hard work and the late nights :)

The latest Node-Red version 1.1.2 is conficting with node-red-contrib-face-recognition@1.3.3
Here's the error message:

Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: C:\Users\*username*\.node-red\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node. Please run command 'npm rebuild @tensorflow/tfjs-node build-addon-from-source' to rebuild the native addon module. If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue. (line:10)

Thanks!

**Comment by thebigpotatoe** [comment]
Hmm, haven't touched this project in a while. Might have to come back and dig into these issues. Its been a pretty fluid year, so I will see when I get time. Pull requests are welcome :)

**Comment by malikhan786** [comment]
Compatibility issue witn Node-Red V1.1.2.


Same issue.

**Comment by thebigpotatoe** [comment]
I think, from playing around with this recently, its an issue with tfjs-node on different OS and architectures not so much node-red. 

The answer is to build tfjs-node from scratch, which I have also been trying to do to no avail on either windows or debian on x86 or arm64. 

Following over there shows that its not really solved yet either. Going to close this issue as its not an issue with this repo, but with tfjs-node.
