### ISSUE TITLE
Other msg value not sent over 

### ISSUE THREAD

**Issue by BankTP** [thebigpotatoe/node-red-contrib-face-recognition#14]
other msg field that has been set before face detection is not send 
or is there any  configuration that I miss.
Thankyou

**Comment by thebigpotatoe** [comment]
I cannot remember, but there is a good chance I clear the message object unintentionally before passing it on. 

There is no config to control this I'm sorry, and I, for the meantime, will not be maintaining this node so it will probably not change soon either.

You may have to use a split and combine node to circumnavigate my crap coding.
