### ISSUE TITLE
Not really an issue. Questions...

### ISSUE THREAD

**Issue by jmorris644** [thebigpotatoe/node-red-contrib-face-recognition#15]
Sorry to use an issue post to ask questions. I did not know how else to do it.

I have been away form the facial recognition process since figuring out the Canvas install error from a year ago already. LIfe just got in the way. :)

2 questions:

1. I see that it has been a little over a year since any updates. I assume for you too that life got in the way? Do you have any plans to continue the maintenance on this project?
2. I would like so spawn a child process on another machine. Actually, a Jetson Nano. It was not evident to me how I could do this if I even could. Thoughts?

Thanks

Joe

**Comment by thebigpotatoe** [comment]
>Sorry to use an issue post to ask questions. I did not know how else to do it.

No worries. One thing I think this site is missing is just a general comment or discussion thread of sorts per repo. 

> I see that it has been a little over a year since any updates. I assume for you too that life got in the way? Do you have any plans to continue the maintenance on this project?

It has been a while, but yes you could say 2020 wasn't the best development year I had haha. I probably won't be maintaining this repo, but I won't archive it either allowing for others to work on it if wanted. There are two reasons; the first is the code is not great, it was early JS days for me and it kind of snow balled to where it is, which has left a lot of duplicated stuff, inefficient methods, and confusing code to maintain or even contribute to.

The second is that through building this node, I found nodes in node-red that have a high dependency on the build env (eg architecture, OS, node version...) are very hard to keep up to date and satisfy everyone's needs easily. Its counter intuitive to what node-red aims to be and you see problems all the time with other nodes ie. mDNS nodes across OS's.

>I would like so spawn a child process on another machine. Actually, a Jetson Nano. It was not evident to me how I could do this if I even could. Thoughts?

If you mean run the node and node-red as standard on a nano, I see no issues besides building Canvas from source like a Raspberry Pi. If you mean you want to run node-red on a base machine and this node on the nano to do the heavy lifting, then no, that is not possible with the way node red works and the way I wrote this node. It is more aligned with distributed cloud computing which is a tricky nut to crack especially if you ware running things at home.

The good news is I got stuck bored in quarantine for the last week, so I decided to develop a docker image that achieves the same outcome as this node! [Check it out here if you would like](https://github.com/thebigpotatoe/face-recognition-docker). 

This solves the issues of architecture, os, and node version and adds more flexibility on how and where people want to run the application. It hooks very easily into node-red with a simple HTTP node too, which means you can run it on a nano and use another node-red machine to send images from. If you are not familiar with docker, I highly recommend getting into it. Its super easy, and I have tried to document how to use the image as best I can for most case. Best part is that I know docker installs on the Nano very easily and allows you to take full advantage of the hardware with ease.
