### ISSUE TITLE
Error to install

### ISSUE THREAD

**Issue by sergey08** [thebigpotatoe/node-red-contrib-face-recognition#19]
Hello,

I have tried to install it from Node red, but I got following error message:

021-06-22T17:53:32.090Z Install : node-red-contrib-face-recognition 2.0.3

2021-06-22T17:53:32.825Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-face-recognition@2.0.3
2021-06-22T17:53:45.352Z [out] 
2021-06-22T17:53:45.352Z [out] > canvas@2.8.0 install /home/pi/.node-red/node_modules/canvas
2021-06-22T17:53:45.352Z [out] > node-pre-gyp install --fallback-to-build
2021-06-22T17:53:45.352Z [out] 
2021-06-22T17:53:46.295Z [err] node-pre-gyp
2021-06-22T17:53:46.296Z [err]  ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-glibc-arm.tar.gz 

Ig I test URL https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-glibc-arm.tar.gz, I got erroer message "Not found"

Thanks in advanced

**Comment by thebigpotatoe** [comment]
What version of nodejs are you running?

**Comment by sergey08** [comment]
Hello,

I have nodejs v14.17.1

Have it any relationship with the missing url  https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-glibc-arm.tar.gz?



Thanks in advanced

**Comment by thebigpotatoe** [comment]
So the pre built binaries only exist for x86 processors for Canvas. However, what should happen is when they are not found node-pre-gyp should default to building them from scratch.

Seems like you are using an arm processor, is it by chance a Pi? If you can give me a little more detail about how you are running node red i should be able to help. Just mention the following:

- Machine running node red: (eg raspberry pi or docker)
- Node version: 14.17.1 
- node red version: 
- install method: Via npm command or node red pallet manager

**Comment by sergey08** [comment]
Thanks in advance

Yes, I am using a Raspberry Pi 4. No docker
Node version: 14.17.1
Node red version: 1.3.5
install method: Node red pallet manager

Regards

**Comment by thebigpotatoe** [comment]
Hmm, very weird. I tried installing it raw on one of my pi's with no issue on node 15 and it works fine.

Did you install the dependencies using this command (might need sudo):

```
apt-get install -y python \
    g++ \
    build-essential \
    libcairo2-dev \
    libjpeg-dev
```

If it still does not build using the pallet manager I suggest installing the package manually by navigating to your `.node-red` folder (usually under `/home` folder I think) and running:

```
npm install node-red-contrib-face-recognition 
```

If that also fails to build canvas from source and 404's, then maybe install canvas manually in the same folder using and repeat the above command:

```
npm install --build-from-source canvas
```

**Comment by thebigpotatoe** [comment]
Closing this issue since its stale. If problems persist please reopen.
