### ISSUE TITLE
Image is not displaying through the image output node 

### ISSUE THREAD

**Issue by satlandau** [thebigpotatoe/node-red-contrib-face-recognition#2]
Hi again :-)
Since version 1.3.1, I get "Invalid image" error message, 
when trying to display image through the image output node.

![image](https://user-images.githubusercontent.com/13630961/69439869-759d2880-0d50-11ea-9bbb-d7320caaade4.png)

I tried to use the "msg.payload=msg.image" or even connect it directly to the the image output node - but no luck. 

Appreciate the effort. Thanks!

**Comment by thebigpotatoe** [comment]
Ah, forgot to update the example. 

I had to change how the message is structured going to version 1.3.0. I will update this now

**Comment by thebigpotatoe** [comment]
Updated in 0cf03d77a84fe67a3dab82f08dcd94b59ad42354
