### ISSUE TITLE
Can't install at Raspberry Pi 4

### ISSUE THREAD

**Issue by kent1026** [thebigpotatoe/node-red-contrib-face-recognition#3]
maybe canvas can not support arm CPU ?

> .921Z Install : node-red-contrib-face-recognition 1.3.2
> 
> 2019-12-26T20:06:46.105Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-face-recognition@1.3.2
> 2019-12-26T20:06:56.979Z [out] 
> 2019-12-26T20:06:56.979Z [out] > canvas@2.6.1 install /home/pi/.node-red/node_modules/canvas
> 2019-12-26T20:06:56.979Z [out] > node-pre-gyp install --fallback-to-build
> 2019-12-26T20:06:56.979Z [out] 
> 2019-12-26T20:06:57.435Z [err] node-pre-gyp
> 2019-12-26T20:06:57.439Z [err]  
> 2019-12-26T20:06:57.439Z [err] WARN
> 2019-12-26T20:06:57.439Z [err]  
> 2019-12-26T20:06:57.439Z [err] Using needle for node-pre-gyp https download
> 2019-12-26T20:06:57.440Z [err]  
> 2019-12-26T20:06:58.469Z [err] node-pre-gyp
> 2019-12-26T20:06:58.469Z [err]  WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v64-linux-glibc-arm.tar.gz 
> 2019-12-26T20:06:58.470Z [err] node-pre-gyp WARN
> 2019-12-26T20:06:58.470Z [err]  Pre-built binaries not found for canvas@2.6.1 and node@10.18.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
> 2019-12-26T20:07:00.999Z [err] Package pixman-1 was not found in the pkg-config search path.
> 2019-12-26T20:07:00.999Z [err] Perhaps you should add the directory containing `pixman-1.pc'
> 2019-12-26T20:07:00.999Z [err] to the PKG_CONFIG_PATH environment variable
> 2019-12-26T20:07:00.999Z [err] No package 'pixman-1' found
> 2019-12-26T20:07:00.999Z [err] gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
> 2019-12-26T20:07:01.016Z [err] gyp
> 2019-12-26T20:07:01.017Z [err]  
> 2019-12-26T20:07:01.017Z [err] ERR! configure error
> 2019-12-26T20:07:01.017Z [err]  
> 2019-12-26T20:07:01.018Z [err] gyp
> 2019-12-26T20:07:01.018Z [err]  ERR! stack
> 2019-12-26T20:07:01.019Z [err]  Error: `gyp` failed with exit code: 1
> 2019-12-26T20:07:01.019Z [err] gyp ERR!
> 2019-12-26T20:07:01.019Z [err]  stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
> 2019-12-26T20:07:01.019Z [err] gyp ERR! 
> 2019-12-26T20:07:01.019Z [err] stack     at ChildProcess.emit (events.js:198:13)
> 2019-12-26T20:07:01.019Z [err] gyp
> 2019-12-26T20:07:01.019Z [err]  ERR! 
> 2019-12-26T20:07:01.019Z [err] stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> 2019-12-26T20:07:01.020Z [err] gyp
> 2019-12-26T20:07:01.020Z [err]  ERR! System Linux 4.19.75-v7l+
> 2019-12-26T20:07:01.020Z [err] gyp
> 2019-12-26T20:07:01.020Z [err]  ERR! command
> 2019-12-26T20:07:01.020Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/pi/.node-red/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
> 2019-12-26T20:07:01.020Z [err] gyp ERR!
> 2019-12-26T20:07:01.020Z [err]  cwd /home/pi/.node-red/node_modules/canvas
> 2019-12-26T20:07:01.021Z [err] gyp 
> 2019-12-26T20:07:01.021Z [err] ERR! node -v
> 2019-12-26T20:07:01.021Z [err]  v10.18.0
> 2019-12-26T20:07:01.021Z [err] gyp
> 2019-12-26T20:07:01.021Z [err]  ERR! 
> 2019-12-26T20:07:01.021Z [err] node-gyp -v v5.0.5
> 2019-12-26T20:07:01.021Z [err] gyp 
> 2019-12-26T20:07:01.021Z [err] ERR! not ok
> 2019-12-26T20:07:01.021Z [err]  
> 2019-12-26T20:07:01.028Z [err] node-pre-gyp
> 2019-12-26T20:07:01.028Z [err]  ERR! build error 
> 2019-12-26T20:07:01.029Z [err] node-pre-gyp
> 2019-12-26T20:07:01.029Z [err]  ERR! stack
> 2019-12-26T20:07:01.029Z [err]  Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/.node-red/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> 2019-12-26T20:07:01.029Z [err] node-pre-gyp 
> 2019-12-26T20:07:01.029Z [err] ERR! stack     at ChildProcess.<anonymous> (/home/pi/.node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> 2019-12-26T20:07:01.029Z [err] node-pre-gyp ERR!
> 2019-12-26T20:07:01.029Z [err]  stack     at ChildProcess.emit (events.js:198:13)
> 2019-12-26T20:07:01.029Z [err] node-pre-gyp ERR!
> 2019-12-26T20:07:01.030Z [err]  stack     at maybeClose (internal/child_process.js:982:16)
> 2019-12-26T20:07:01.030Z [err] node-pre-gyp ERR!
> 2019-12-26T20:07:01.030Z [err]  stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 2019-12-26T20:07:01.031Z [err] node-pre-gyp
> 2019-12-26T20:07:01.031Z [err]  ERR! System Linux 4.19.75-v7l+
> 2019-12-26T20:07:01.031Z [err] node-pre-gyp
> 2019-12-26T20:07:01.031Z [err]  ERR! command
> 2019-12-26T20:07:01.031Z [err]  "/usr/bin/node" "/home/pi/.node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> 2019-12-26T20:07:01.031Z [err] node-pre-gyp ERR!
> 2019-12-26T20:07:01.031Z [err]  cwd
> 2019-12-26T20:07:01.031Z [err]  /home/pi/.node-red/node_modules/canvas
> 2019-12-26T20:07:01.031Z [err] node-pre-gyp
> 2019-12-26T20:07:01.031Z [err]  ERR! 
> 2019-12-26T20:07:01.032Z [err] node -v v10.18.0
> 2019-12-26T20:07:01.032Z [err] node-pre-gyp 
> 2019-12-26T20:07:01.032Z [err] ERR! node-pre-gyp -v
> 2019-12-26T20:07:01.032Z [err]  v0.11.0
> 2019-12-26T20:07:01.032Z [err] node-pre-gyp
> 2019-12-26T20:07:01.032Z [err]  ERR! not ok
> 2019-12-26T20:07:01.032Z [err]  
> 2019-12-26T20:07:01.033Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/.node-red/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> 2019-12-26T20:07:01.723Z [err] npm
> 2019-12-26T20:07:01.723Z [err]  ERR! code ELIFECYCLE
> 2019-12-26T20:07:01.724Z [err] npm
> 2019-12-26T20:07:01.724Z [err]  ERR! errno
> 2019-12-26T20:07:01.725Z [err]  1
> 2019-12-26T20:07:01.730Z [err] npm
> 2019-12-26T20:07:01.732Z [err]  ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
> 2019-12-26T20:07:01.732Z [err] npm ERR! Exit status 1
> 2019-12-26T20:07:01.732Z [err] npm ERR! 
> 2019-12-26T20:07:01.732Z [err] npm ERR! Failed at the canvas@2.6.1 install script.
> 2019-12-26T20:07:01.732Z [err] npm ERR!
> 2019-12-26T20:07:01.732Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
> 2019-12-26T20:07:01.791Z [err] 
> 2019-12-26T20:07:01.792Z [err] npm ERR! A complete log of this run can be found in:
> 2019-12-26T20:07:01.792Z [err] npm ERR!     /home/pi/.npm/_logs/2019-12-26T20_07_01_770Z-debug.log
> 2019-12-26T20:07:01.823Z rc=1

**Comment by thebigpotatoe** [comment]
Seems like there arn't any pre-compiled binaries for the raspberry pi 4 with your operating system;

> 2019-12-26T20:06:58.470Z [err] Pre-built binaries not found for canvas@2.6.1 and node@10.18.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)

You may have to [compile canvas yourself](https://github.com/Automattic/node-canvas/wiki/Installation%3A-Ubuntu-and-other-Debian-based-systems) and its dependencies in your .node-red folder. I haven't installed it on a Pi yet as mine has  not been playing ball recently, so i'm not 100% sure exactly how to get canvas going exactly but this may help.

**Comment by kent1026** [comment]
Thanks, it's work. but when I use npm install @tensorflow/tfjs-node
then node-red debug print  :
[Face-api.js : 75ff9e47.e428c : Child Node] - Failed to load in TensorFlow.js for Node.js in child_process: TypeError: tfjs_core_1.registerKernel is not a function"

and Node-Red print error message:

Flows stopped due to missing node types.
face-api-compute
face-api-input


How can i do ?
Thanks.

**Comment by thebigpotatoe** [comment]
To clarify it works without tfjs-node?

With tfjs-node though, having a look on [the tfjs-node GitHub page](https://github.com/tensorflow/tfjs/tree/master/tfjs-node#rebuild-the-package-on-raspberry-pi) it states you need to rebuild the package on raspberry pi using `rebuild @tensorflow/tfjs-node --build-from-source`

**Comment by kent1026** [comment]
Thanks, but I can't rebuild tensorflow

it print:
```bash
pi@raspberrypi:~/.node-red$ npm rebuild @tensorflow/tfjs-node --build-from-source                                                                               │··········
                                                                                                                                                                │··········
> @tensorflow/tfjs-node@1.5.1 install /home/pi/.node-red/node_modules/@tensorflow/tfjs-node                                                                     │··········
> node scripts/install.js                                                                                                                                       │··········
                                                                                                                                                                │··········
CPU-linux-1.5.1.tar.gz                                                                                                                                          │··········
* Downloading libtensorflow                                                                                                                                     │··········
(node:4484) UnhandledPromiseRejectionWarning: Error: Unsupported system: cpu-linux-arm                                                                          │··········
    at getPlatformLibtensorflowUri (/home/pi/.node-red/node_modules/@tensorflow/tfjs-node/scripts/install.js:95:11)                                             │··········
    at downloadLibtensorflow (/home/pi/.node-red/node_modules/@tensorflow/tfjs-node/scripts/install.js:129:7)                                                   │··········
    at async run (/home/pi/.node-red/node_modules/@tensorflow/tfjs-node/scripts/install.js:190:5)                                                               │··········
(node:4484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch │··········
block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)                                                                         │··········
(node:4484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the│··········
 Node.js process with a non-zero exit code.                                                                                                                     │··········
@tensorflow/tfjs-node@1.5.1 /home/pi/.node-red/node_modules/@tensorflow/tfjs-node ```

**Comment by thebigpotatoe** [comment]
These errors are not unique to this repo, and as I have stated, I have not attempted to run this on a raspberry pi 4. So I will be closing this issue as this space should be used for tracking issues unique to this repo. If you have an issue during running or using this repo feel free to pop open another one.

Some help though; I am still earning JS and how to manage it through NPM myself, but your error messages seem to suggest that the pi and the operating system you are running are not supported by the required libraries. My suggestion is to browse the tfjs-node repo and face-api.js repo for raspberry pi issues and answers.

I have noticed that you are running node 10.18.0 from the above messages, so I would suggest updating that for a start. Then you may be able to follow those steps in the link you supplied.

When I was building this, I found that the basic Face-api.js worked out of the box easily, but getting tfjs-node to run as well was painful. I am using windows, and as in the readme, I found a specific setup that worked for me. You will need to do the same as I have not used a pi for testing.
