### ISSUE TITLE
Text showing up as boxes on result image

### ISSUE THREAD

**Issue by maxi1134** [thebigpotatoe/node-red-contrib-face-recognition#5]
Hi there!

I just tried this repo after talking with the OP on reddit.
But it seems like the results are coming through with a weird encoding (Or so it looks).

Is there anything that I could do to fix this?

![image](https://user-images.githubusercontent.com/1342643/73364083-ed6b6000-4277-11ea-84f4-64d6b9cae27c.png)

**Comment by thebigpotatoe** [comment]
Very weird,

Perhaps Canvas is not fully supported or something on your VM. What operating system are you using?

**Comment by maxi1134** [comment]
I run on Ubuntu!

**Comment by thebigpotatoe** [comment]
Huh, well I'm glad its working elsewhere in the flow. At least you can use the functionality then.

I haven't run it on Ubuntu yet, so I really not sure about why there is no valid text, but I think you may be on to something with the missing font. Let me have a look at the libraries and see if they use anything specific.

**Comment by thebigpotatoe** [comment]
Seems like the text is drawn by Face.api itself using the function `faceapi.draw.DrawTextField()`. With zero options passed to this the default is "Georgia" which from a quick google is a Microsoft TrueType font not available on Ubuntu. 

Again, I do not have an Ubuntu rig setup at the moment, so there are two options I think if you want to solve this. Either install "Georgia" or you can modify the source for the node in two places.

Seems [this link](https://www.makeuseof.com/tag/how-to-install-microsoft-core-fonts-in-ubuntu-linux/) may help install new fonts in Ubuntu.

If you want to modify the the source, you just need to replace the following on lines 683 of `face-api.js` and 326 of `face-api-cmd.js` in the recognition nodes main folder;

``` javascript

new faceapi.draw.DrawTextField(
    [ 
        ...expressionsLabel,
        ...ageGenderLabel,
        ...recognitionLabel
    ],
    result.detection.box.bottomLeft
).draw(outImg)

```

 with this;

``` javascript

const drawOptions = {
	fontStyle: "Ubuntu"
}
new faceapi.draw.DrawTextField(
	[ 
		...expressionsLabel,
		...ageGenderLabel,
		...recognitionLabel
	],
	result.detection.box.bottomLeft,
	drawOptions
).draw(outImg)

```

You can change the font style to one that works, but as far as I can tell, this should work on Ubuntu. I don't know much about font compatibility, but if this works I will add it to the code and change the font to one that hopefully works across platforms.

Let me know how you go.

**Comment by maxi1134** [comment]
Installing the fonts did not resolve the problem.

As for changing the code, I looked for 20 minutes and cannot find where they are located.
I'll try again tomorrow.

**Comment by thebigpotatoe** [comment]
Ah damn, 

Quick read online says that the standard Ubuntu install of node red should be in "/usr/local/bin" under I'm assuming a .node-red folder or something.

Wether or not your install is in "/usr/local/bin", there should be a .node-red folder somewhere and in it it should have a "node-modules" folder which will have all installed nodes including this one. The files stated should be in there.

**Comment by maxi1134** [comment]
I don't seem to find anything related to this under .node-red/node-Modules.

This is the content of my folder:

![image](https://user-images.githubusercontent.com/1342643/73424503-010cda00-42fd-11ea-9479-95b3d6af1242.png)

**Comment by thebigpotatoe** [comment]
I did a bit more reading, seems it may be in "/home/__USERNAME__/.node-red", where __USERNAME__ is your current login name of course. This is where your flow files and such should be too. Got this from [here](http://www.steves-internet-guide.com/installing-node-red/).

**Comment by maxi1134** [comment]
So, Since my node-red installation was very ghetto.

I created a new one on a new machine.

I replaced the files as you asked me, but the squares continue :(

**Comment by thebigpotatoe** [comment]
That's really annoying. 

Last thing I can think of is to [check which fonts come installed for you](https://askubuntu.com/questions/552979/how-can-i-determine-which-fonts-are-installed-from-the-command-line-and-what-is), then edit the files as I suggest above replacing the word "Ubuntu" in the line `fontStyle: "Ubuntu"` with a valid font from that list.

This line is where you can select a system font for drawing the text. I have changed it between "Georgia" and "Arial" on windows successfully. What was even more interesting for me was when I tested it with "Ubuntu" it fell back to the system font of "sans serif". So I'm wondering why your install of "Ubuntu" does not fall back to something. Is there anything in your node red output window to suggest it cannot find a font?

**Comment by maxi1134** [comment]
Welp, I was missing FontConfig.

Ran sudo apt-get install FontConfig and now everything is working! (Although inference time is well over 30 seconds)

**Comment by thebigpotatoe** [comment]
Ah awesome. Glad that's fixed.

The inference time issue is due to the tensforflow c++ background not running. As stated in the readme, you will need to find a combination of Node.js, @tensorflow/tfjs-node, and face-api.js.

To find the right combination for windows, I just continuously installed and uninstalled the @tensorflow/tfjs-node package using NPM as it was the easiest. Give the [versions suggested in the readme](https://github.com/thebigpotatoe/node-red-contrib-face-recognition#tensorflow-for-nodejs-optional) a go and see if your inference times change.
