### ISSUE TITLE
How to train faces for facial recognition.

### ISSUE THREAD

**Issue by maxi1134** [thebigpotatoe/node-red-contrib-face-recognition#6]
Hi there! I just started using this node and am having a hard time understanding how to tech faces linked to names for facial recognition.

I have tried adding a descriptor called Sheldon.jpg to detect the face of sheldon in the demo, but it doesn't seem to work.

Am I doing something wrong?

**Comment by thebigpotatoe** [comment]
Perhaps this is an issue with the documentation. But the steps required are;

- create a `compute node` inside of an added `input node`
- check the box "**recognise** a face in the image"
- Then when the "Add image" button pops up click that to select images (you may select one or many). Any image selected should contain the face of the individual you would like to recognise only.
- When selection is done, simply click "add" or "update" in the editor which should then send the images to the node red server for processing.
- Your node red instance will freeze for a bit to compute the descriptors of the faces you have supplied and then save them. (note that you will need write permissions to your .node-red folder)
- After that, make sure your compute node is selected in your input nodes, then simply pass an image to the node for inference.

**Comment by thebigpotatoe** [comment]
If you are having issues, make sure to check the logs as well. If you get stuck just paste them here as they should indicate the issue.

**Comment by maxi1134** [comment]
And, follow up, is there a way to teach more that 10 faces? I want to use this for when I host parties to announces who's as the door. Which mean I would need to teach about 50 faces.

**Comment by thebigpotatoe** [comment]
Currently there is no way to add more than 10 compute nodes to an input node. This is because the HTML is currently statically type for the input node due to the way the front end had to be written. I may change this in the future so this limitation wont exist.

A work around is to add as many input nodes as you desire and sending the same input to each at the same time.

**Comment by wifff** [comment]
Hi,
first things first: thank you very much for this great piece of software!
Just installed it on a Raspi 4 and it just worked !

I want to replace and expand a webcam system written in Python
https://newgoldeneye.blogspot.com/2020/05/webcam-flugplatz.html

Now I am looking for a "face-blur" function. Is that already in the pipeline ?
I am also looking for the coordinates (x,y) of the bounding boxes of the faces found in an image.
To write a function on my own I would need these coordinates.
There is "payload.face_recon.faces[0].imageDims._width" and _height but I was unable to find the x,y values of the corner of the box.
Any help very appreciated !

Best regards & Healthy New Year !
Wolfgang
