### ISSUE TITLE
Has anybody succeeded in installing on Raspberry PI?

### ISSUE THREAD

**Issue by agoralive** [thebigpotatoe/node-red-contrib-face-recognition#7]
My rasp is 3B+

How do I success here, any tutorial?

**Comment by thebigpotatoe** [comment]
Either it will or will not work out of the box. I haven't managed to get around to installing it on my Pi yet, however I know it does install on flavours of linux. 

You may have to compile canvas from source and potentially the other libraries as well if there are no pre compiled binaries for the Pi on your choice of OS.

**Comment by thebigpotatoe** [comment]
For those struggling, Canvas must be installed from source for the Pi. This requires the following to be installed;

```console
sudo apt-get update -y  && \
sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
```

And you may have to install it from scratch in your `.node-red` folder;

```console
npm install --build-from-source canvas
```
